Add plugin system
IamShobe/elrados pull request #2
Opened 2019-02-15 16:07 UTC by IamShobe

2019-02-15 20:24 UTC, gregoil requested changes
Add documentation for the new additions in the README. 
Also I'd like to see how the declaration of plugins looks

2019-02-15 20:24 UTC, gregoil commented on src/elrados/backend/main.py
> +    if "elrados" not in yaml_configuration:
Just use ```get``` with default value

2019-02-15 20:24 UTC, gregoil commented on src/elrados/backend/main.py
> +    yaml_configuration = yaml_configuration["elrados"]
It returns ```AttrDict``` either way, no?

2019-02-15 20:24 UTC, gregoil commented on src/elrados/backend/main.py
> +        if default_resource is None else default_resource
Standard ```if``` section might look better here

2019-02-16 07:52 UTC, IamShobe commented on src/elrados/backend/main.py
> +    yaml_configuration = yaml_configuration["elrados"]
yes y?

2019-02-16 11:02 UTC, gregoil requested changes
What about the README file?

2019-02-16 14:45 UTC, gregoil approved these changes

2019-02-16 14:57 UTC, merged